[package]
name = "mopp-2018-t3-himeno-rust"
version = "0.1.0"
authors = ["Fritz Louis Wilke <fritz.wilke@tu-dresden.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13.0"